In [1]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [2]:
data = {
    "feature_1" : [1,2,3,4,5],
    "feature_2" : [5,4,2,3,1],
    "label" : [0,0,1,1,0]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   feature_1  feature_2  label
0          1          5      0
1          2          4      0
2          3          2      1
3          4          3      1
4          5          1      0

In [5]:
x = df[["feature_1","feature_2"]]
y = df["label"]

In [6]:
x

   feature_1  feature_2
0          1          5
1          2          4
2          3          2
3          4          3
4          5          1

In [ ]:
mod = Sequential()
mod.add(Dense(10,input_dim =2,activation="relu"))
mod.add(Dense(1,activation="sigmoid"))

c:\gen\.conda\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [11]:
mod.compiled_loss

In [12]:
mod.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [14]:
mod.fit(x,y,verbose = 2, epochs= 100, batch_size= 1)

Epoch 1/100
5/5 - 1s - 160ms/step - accuracy: 0.4000 - loss: 0.7092
Epoch 2/100
5/5 - 0s - 9ms/step - accuracy: 0.4000 - loss: 0.7007
Epoch 3/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6951
Epoch 4/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6918
Epoch 5/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6873
Epoch 6/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6841
Epoch 7/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6802
Epoch 8/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6762
Epoch 9/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6736
Epoch 10/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6704
Epoch 11/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6667
Epoch 12/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6635
Epoch 13/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6604
Epoch 14/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6589
Epoch 15/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6552
Epoch 16/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6529
Epoch 17/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6507
Epoch 18/100
5/5 - 0s - 7ms/step - accuracy: 0.4000 - loss: 0.6476
Epoch 19/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6453
Epoch 20/100
5/5 - 0s - 7ms/step - accuracy: 0.4000 - loss: 0.6437
Epoch 21/100
5/5 - 0s - 8ms/step - accuracy: 0.4000 - loss: 0.6418
Epoch 22/100
5/5 - 0s - 7ms/step - accuracy: 0.4000 - loss: 0.6389
Epoch 23/100
5/5 - 0s - 7ms/step - accuracy: 0.4000 - loss: 0.6367
Epoch 24/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.6341
Epoch 25/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.6319
Epoch 26/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6307
Epoch 27/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.6280
Epoch 28/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6259
Epoch 29/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6245
Epoch 30/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6216
Epoch 31/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.6190
Epoch 32/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6167
Epoch 33/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.6147
Epoch 34/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6129
Epoch 35/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6110
Epoch 36/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.6084
Epoch 37/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6074
Epoch 38/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6045
Epoch 39/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.6027
Epoch 40/100
5/5 - 0s - 9ms/step - accuracy: 0.6000 - loss: 0.6020
Epoch 41/100
5/5 - 0s - 9ms/step - accuracy: 0.6000 - loss: 0.5988
Epoch 42/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5972
Epoch 43/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5949
Epoch 44/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5933
Epoch 45/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5913
Epoch 46/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5897
Epoch 47/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5874
Epoch 48/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5864
Epoch 49/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5838
Epoch 50/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5817
Epoch 51/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5797
Epoch 52/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5776
Epoch 53/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5761
Epoch 54/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5739
Epoch 55/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5718
Epoch 56/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5699
Epoch 57/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5681
Epoch 58/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5662
Epoch 59/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5652
Epoch 60/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5619
Epoch 61/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5603
Epoch 62/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5581
Epoch 63/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5564
Epoch 64/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5555
Epoch 65/100
5/5 - 0s - 10ms/step - accuracy: 0.6000 - loss: 0.5548
Epoch 66/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5522
Epoch 67/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5510
Epoch 68/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5495
Epoch 69/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5476
Epoch 70/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5463
Epoch 71/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5452
Epoch 72/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5436
Epoch 73/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5427
Epoch 74/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5412
Epoch 75/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5398
Epoch 76/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5382
Epoch 77/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5366
Epoch 78/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5359
Epoch 79/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5348
Epoch 80/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5338
Epoch 81/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5321
Epoch 82/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5311
Epoch 83/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5297
Epoch 84/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5291
Epoch 85/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5283
Epoch 86/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5269
Epoch 87/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5260
Epoch 88/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5247
Epoch 89/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5239
Epoch 90/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5231
Epoch 91/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5212
Epoch 92/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5207
Epoch 93/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5194
Epoch 94/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5182
Epoch 95/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5173
Epoch 96/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5166
Epoch 97/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5152
Epoch 98/100
5/5 - 0s - 8ms/step - accuracy: 0.6000 - loss: 0.5142
Epoch 99/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5137
Epoch 100/100
5/5 - 0s - 7ms/step - accuracy: 0.6000 - loss: 0.5122

In [17]:
test_data = np.array([[0.2, 0.4]])
prediction = mod.predict(test_data)
predicted_label = (prediction > 0.5).astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

In [20]:
prediction

array([[0.490343]], dtype=float32)